name: Build

on:
  push:
    branches:
      - master
    paths:
      - "**.ts"
      - "package.json"
      - "yarn.lock"
      - "tsconfig.json"

jobs:
  build:
    name: Transpile Typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup workspace
        run: yarn install --frozen-lockfile

      - name: Transpile
        run: yarn run build

      - name: Push changes
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "build: Transpile" || echo "No changes to commit"
          git push origin HEAD